/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2017-11-30 09:34:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1500365274660L));
    _jspx_dependants.put("jar:file:/F:/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/FinacialSys/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>主页</title>\r\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"assets/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/nav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/home.css\">\r\n");
      out.write("    <link href=\"assets/img/favicon-20170803111016817.ico\" rel=\"SHORTCUT ICON\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/homeBg.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("       <nav id=\"menu\" class=\"navbar\" style=\"height:78px\">\r\n");
      out.write("        <ul id=\"nav-list\">\r\n");
      out.write("          <li class=\"li-1\"><a href=\"home\" style=\"font-size: 14px\">主页</a></li>\r\n");
      out.write("          <li class=\"li-2\"><a href=\"finacialCreate\" style=\"font-size: 14px\">收支创建</a></li>\r\n");
      out.write("          <li class=\"li-3\"><a href=\"expandShow\" style=\"font-size: 14px\">我的收支</a></li>\r\n");
      out.write("          <li class=\"li-4\"><a href=\"data\" style=\"font-size: 14px\">数据分析</a></li>\r\n");
      out.write("          <li class=\"li-5\"><a href=\"plan\" style=\"font-size: 14px\">我的计划</a></li>\r\n");
      out.write("          <li class=\"li-6\"><a href=\"userGroup\" style=\"font-size: 14px\">我的家庭组</a></li>\r\n");
      out.write("          <div class=\"current\">\r\n");
      out.write("              <div class=\"top-arrow\"></div>   \r\n");
      out.write("              <div class=\"current-back\"></div>\r\n");
      out.write("              <div class=\"bottom-arrow\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div id=\"nav-right\" style=\"padding-top:1px;\">\r\n");
      out.write("\t\t   <a href=\"userSetting\" id=\"user\">\r\n");
      out.write("\t\t   \t\t<span id=\"pic\" style=\"background-image: url(assets/img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userPic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\"></span>\r\n");
      out.write("\t\t   \t\t<span id=\"name\" style=\"font-size: 14px;padding-top: 5px;\">\r\n");
      out.write("\t\t   \t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userNickname.length() > 4 ? user.userNickname.substring(0,4).concat(\"...\"): user.userNickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \r\n");
      out.write("\t\t   \t\t</span>\r\n");
      out.write("\t\t   \t</a>\t\r\n");
      out.write("  \t       <a class=\"fa fa-sign-out\" id=\"log-out\" aria-hidden=\"true\" href=\"logout\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write(" <div class=\"bg bg-box-1\"></div>\r\n");
      out.write("\t<div class=\"bg bg-box-2\"></div>\r\n");
      out.write("\t<div class=\"bg bg-box-3\"></div>\r\n");
      out.write("\t<div class=\"bg bg-box-4\"></div>\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<div class=\"text home3 hide\">\r\n");
      out.write("\t\t\t\t\t<p>更多精彩</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"Team\">\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 80px;padding-top:160px\">敬请期待！</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 80px\">我们期待你的加入！！！φ(≧ω≦*)♪</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<div class=\"text home2 hide\">\r\n");
      out.write("\t\t\t\t\t<p>关于用户</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"Team\">\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 20px;padding-top:80px\" class=\"th1\">适合于所有希望对自己财物有一个统一的、形象的计划的人群</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 20px\" class=\"th1\">┗|｀O′|┛ 嗷~~</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<div class=\"text home1 hide\">\r\n");
      out.write("\t\t\t\t\t<p>关于产品</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"Team\">\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 80px;padding-top:70px\" class=\"th\">这是一款基于web家庭财务管理系统</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 20px;padding-top:32px\" class=\"th\">  家庭是一个小小的管理单元，财务的收入与支出是一个零碎而又与切身利益相关的问题</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 20px\" class=\"th\">  用户可以随时记录自己的收入、支出等信息，另外为了保护自己的隐私，还可以设置密码。</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 20px\" class=\"th\">  我们产品可以有效地帮助合理规划和支配资金，可以通过分析来获得家庭成员在一段时期内的消费和收入信息，是家庭理财的好帮手</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"curr\">\r\n");
      out.write("\t\t\t\t<div class=\"text home\">\r\n");
      out.write("\t\t\t\t\t<p>关于团队</p>\r\n");
      out.write("\t\t\t\t\t<!-- <p>团队组成:</p><br/> -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"Team\">\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 40px;padding-top:80px\">成员：彭璨麒  电子科技大学信软学院</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 130px;padding-top:20px\">唐浩 电子科技大学信软学院</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 130px;padding-top:20px\">江洋 电子科技大学信软学院</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 130px;padding-top:20px\">陈振宁 电子科技大学信软学院</li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"padding-left: 130px;padding-top:20px\">何佳霓 电子科技大学信软学院</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"assets/js/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t(function(){\r\n");
      out.write("\t\t$('#wrap > ul > li').mouseover(function(){\r\n");
      out.write("\t\t\tif(!$(this).hasClass('curr')){\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li').removeClass('curr');\r\n");
      out.write("\t\t\t\t$(this).addClass('curr');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 切换背景\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li').each(function(index){\r\n");
      out.write("\t\t\t\t\tif($(this).hasClass('curr')){\r\n");
      out.write("\t\t\t\t\t\t$('.bg').fadeOut(300);\r\n");
      out.write("\t\t\t\t\t\t$('.bg:eq(' + index + ')').fadeIn(500);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('.curr').stop().animate({\r\n");
      out.write("\t\t\t\t\twidth: 700\r\n");
      out.write("\t\t\t\t}, 500, 'linear');\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li').not('.curr').stop().animate({\r\n");
      out.write("\t\t\t\t\twidth: 100\r\n");
      out.write("\t\t\t\t}, 500, 'linear');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t$('#wrap > ul > li > div.home1').mouseover(function() {\r\n");
      out.write("\t\t\tif($(this).hasClass('hide')){\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home1').removeClass('hide');\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home2').addClass('hide');\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home3').addClass('hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#wrap > ul > li > div.home2').mouseover(function() {\r\n");
      out.write("\t\t\tif($(this).hasClass('hide')){\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home1').addClass('hide');\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home2').removeClass('hide');\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home3').addClass('hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#wrap > ul > li > div.home3').mouseover(function() {\r\n");
      out.write("\t\t\tif($(this).hasClass('hide')){\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home1').addClass('hide');\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home2').addClass('hide');\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home3').removeClass('hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#wrap > ul > li > div.home').mouseover(function() {\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home1').addClass('hide');\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home2').addClass('hide');\r\n");
      out.write("\t\t\t\t$('#wrap > ul > li > div.home3').addClass('hide');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})()\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
